number_int: 42

list:
- 1
- 2
- 3 
- 4
- 5
- 6
number_int2: 422
# Starting Positions Link 7 R
#x: 0,362747
#y: −0,317753
#z: 0,246492

# Start values for Link 7 L:
#x: 0,379863
#y: 0,319631
#z: 0,269617
posestamp1:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.288638
      y: -0.328583
      z: 0.478045
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp2:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: -0.25155
      z: 0.200519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp3:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.388631
      y: -0.328582
      z: 0.246492
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

#tester av orientation
#original orientations
#   x: 0.715402
#   y: -0.201775
#   z: 0.634136
#   w: -0.212975

#posestamp5:
#  header:
#    stamp: 0
#    frame_id: "yumi_base_link"
#  pose:
#    position:
#      x: 0.388638
#      y: 0.319631
#      z: 0.026000
#    orientation:

#      x: 0.1786622
#     y: 0.7361919
#      z: 0.1854725
#      w: 0.6258604

#Dröm orientations
#      x: 0
#      y: 0.7071068
#      z: 0.
#      w: 0.7071068

#      x: 0
#      y: 1
#      z: 0
#      w: -0.000000







posestamp4:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.493576
      y: 0.317959
      z: 0.234764
    orientation:
      x: 0
      y: 0
      z: 0
      w: 1


posestamp5:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.493576
      y: 0.317959
      z: 0.234764
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5



posestamp6:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: 0.25155
      z: 0.400519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975


kdl_manager:
  eps: 0.01
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 0
  ik_angle_tolerance: 0.01
  ik_pos_tolerance: 0.005
  gravity_in_base_link: [0, 0, -9.8]


