number_int: 42

list:
- 1
- 2 
- 4
- 5
number_int2: 422

posestamp1:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.288638
      y: 0.328583
      z: 0.478045
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp2:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: -0.25155
      z: 0.400519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975



posestamp3:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.488638
      y: 0.328583
      z: 0.478045
    orientation:
      x: 0.015402
      y: -0.201775
      z: 0.634136
      w: -0.212975
