number_int: 42

list:
- 1
- 2
- 3 
- 4
- 5
- 6
number_int2: 422
# Starting Positions Link 7 R
#x: 0,362747
#y: −0,317753
#z: 0,246492

# Start values for Link 7 L:
#x: 0,379863
#y: 0,319631
#z: 0,269617
posestamp1:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.288638
      y: -0.328583
      z: 0.478045
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp2:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: 0.25155
      z: 0.400519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975



posestamp3:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.388631
      y: -0.328582
      z: 0.246492
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp4:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position: 
      x: 0.379863
      y: 0.319631
      z: 0.269617
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975


posestamp5:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.388638
      y: -0.328583
      z: 0.478045
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp6:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: 0.25155
      z: 0.400519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

