number_int: 42

list:
- 1
- 2
- 3 
- 4
- 5
- 6
number_int2: 422
# Starting Positions Link 7 R
#x: 0,362747
#y: −0,317753
#z: 0,246492

# Start values for Link 7 L:
#x: 0,379863
#y: 0,319631
#z: 0,269617
posestamp1:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.288638
      y: -0.328583
      z: 0.478045
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp2:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: -0.25155
      z: 0.200519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp3:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.388631
      y: -0.328582
      z: 0.246492
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

#tester av orientation
#original orientations
#   x: 0.715402
#   y: -0.201775
#   z: 0.634136
#   w: -0.212975

#posestamp5:
#  header:
#    stamp: 0
#    frame_id: "yumi_base_link"
#  pose:
#    position:
#      x: 0.388638
#      y: 0.319631
#      z: 0.026000
#    orientation:
#      x: 0
#      y: 1
#      z: 0
#      w: -0.000000





# x verkar styra end jointen upp och nedåt
# testat x= 0.521200 testat 0.121200 och mindre tal ger mer "uppåt"
# x=1 krashar 0.8 krash 0.75 krash
#olika positioner tillåter olika orientations.... 
#Y tester. Verkar som det är höger och vänster
#-0.401775 funkar inte -0.3 funkar inte. -0.1 däremot
#+0.1 funkar +0.2 funkar +0.3 funkar inte
#z test
#+0.531 funkar inte på pose 5....

#Allt ovanför är en lögn
#X=1 Är rakt ner 

posestamp4:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.385236
      y: 0.339993
      z: 0.264575
    orientation:
      x: 0.6613301
      y: -0.3410208
      z: 0.6637714
      w: 0.0758612

posestamp5:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.259721
      y: 0.120201
      z: 0.211012
    orientation:
      x: 0.3826834
      y: 0
      z: 0
      w: 0.9238795

posestamp6:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.356709
      y: 0.25155
      z: 0.400519
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

