number_int: 42

list:
- 1
- 2
- 3 
- 4
- 5
- 6
number_int2: 422
# Starting Positions Link 7 R
#x: 0,362747
#y: −0,317753
#z: 0,246492

# Start values for Link 7 L:
#x: 0,379863
#y: 0,319631
#z: 0,269617

#RIGHT ARM


posestamp1:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.493576
      y: -0.317959
      z: 0.234764
    orientation:
      x: 0
      y: 0
      z: 0
      w: 1

posestamp2:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.493576
      y: -0.317959
      z: 0.1
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5

posestamp3:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.388631
      y: -0.328582
      z: 0.246492
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp4:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.30000
      y: -0.1
      z: 0.2
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp5:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.30000
      y: -0.1
      z: 0.2
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975

posestamp6:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.33000
      y: -0.1
      z: 0.3
    orientation:
      x: 0.715402
      y: -0.201775
      z: 0.634136
      w: -0.212975



#LEFT ARM




posestamp7:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.335190
      y: 0.288306
      z: 0.1
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5


posestamp8:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.359047
      y: 0.298306
      z: 0.05
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5
   

posestamp9:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.399999
      y: 0.298306
      z: 0.01
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5


posestamp10:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.34000
      y: 0.15
      z: 0.1
    orientation:
      x: -0.5
      y: 0.5
      z: -0.5
      w: 0.5

posestamp11:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.34000
      y: 0.15
      z: 0.2
    orientation:
      x: 0.7071068
      y: 0.
      z: 0.
      w: 0.7071068


posestamp12:
  header:
    stamp: 0
    frame_id: "yumi_base_link"
  pose:
    position:
      x: 0.34000
      y: 0.15
      z: 0.3
    orientation:
      x: 0.7071068
      y: 0.
      z: 0.
      w: 0.7071068



kdl_manager:
  eps: 0.01
  max_tf_attempts: 10
  ikvel_solver: nso
  nso_weight: 0
  ik_angle_tolerance: 0.01
  ik_pos_tolerance: 0.005
  gravity_in_base_link: [0, 0, -9.8]


